insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('GsmCell', 'PM_E_EBSG:((3)):PM_E_EBSG_CELL:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_cell', 'PM_E_EBSG:((3)):PM_E_EBSG_CELL:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('Trx', 'PM_E_EBSG:((3)):PM_E_EBSG_TRX:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_trx', 'PM_E_EBSG:((3)):PM_E_EBSG_TRX:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_apn', 'PM_E_EBSS:((2)):PM_E_EBSS_APN:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('APN', 'PM_E_EBSS:((2)):PM_E_EBSS_APN:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('CELL', 'PM_E_EBSS:((2)):PM_E_EBSS_CELL:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_cell', 'PM_E_EBSS:((2)):PM_E_EBSS_CELL:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('GGSN', 'PM_E_EBSS:((2)):PM_E_EBSS_GGSN:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_ggsn', 'PM_E_EBSS:((2)):PM_E_EBSS_GGSN:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('HLR', 'PM_E_EBSS:((2)):PM_E_EBSS_HLR:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_hlr', 'PM_E_EBSS:((2)):PM_E_EBSS_HLR:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('HNI', 'PM_E_EBSS:((2)):PM_E_EBSS_HNI:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_hni', 'PM_E_EBSS:((2)):PM_E_EBSS_HNI:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('HZI', 'PM_E_EBSS:((2)):PM_E_EBSS_HZI:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_hzi', 'PM_E_EBSS:((2)):PM_E_EBSS_HZI:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('RA', 'PM_E_EBSS:((2)):PM_E_EBSS_RA:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_ra', 'PM_E_EBSS:((2)):PM_E_EBSS_RA:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_sa', 'PM_E_EBSS:((2)):PM_E_EBSS_SA:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('SA', 'PM_E_EBSS:((2)):PM_E_EBSS_SA:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('SGSN', 'PM_E_EBSS:((2)):PM_E_EBSS_SGSN:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_sgsn', 'PM_E_EBSS:((2)):PM_E_EBSS_SGSN:ebs', 'For SGSN');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('TAC', 'PM_E_EBSS:((2)):PM_E_EBSS_TAC:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_tac', 'PM_E_EBSS:((2)):PM_E_EBSS_TAC:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('TACSVN', 'PM_E_EBSS:((2)):PM_E_EBSS_TACSVN:ebs', '');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_tacsvn', 'PM_E_EBSS:((2)):PM_E_EBSS_TACSVN:ebs', 'For MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('MOM_cell', 'PM_E_EBSW:((2)):PM_E_EBSW_CELL:ebs', 'for MOM');
insert into DefaultTags (TAGID, DATAFORMATID, DESCRIPTION) values ('UtranCell', 'PM_E_EBSW:((2)):PM_E_EBSW_CELL:ebs', '');
