insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSG:((3))', 'create view SELECT_PM_E_EBSG_AGGLEVEL', '1', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_PM_E_EBSG_AGGLEVEL'') > 0 DROP VIEW SELECT_PM_E_EBSG_AGGLEVEL BEGIN create view SELECT_PM_E_EBSG_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS) as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE WHERE TIMELEVELBH = ''DAYBH'' commit grant select on SELECT_PM_E_EBSG_AGGLEVEL to dcbo END', '1');
insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSS:((2))', 'create view SELECT_PM_E_EBSS_AGGLEVEL', '1', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_PM_E_EBSS_AGGLEVEL'') > 0 DROP VIEW SELECT_PM_E_EBSS_AGGLEVEL BEGIN create view SELECT_PM_E_EBSS_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS) as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE WHERE TIMELEVELBH = ''DAYBH'' commit grant select on SELECT_PM_E_EBSS_AGGLEVEL to dcbo END', '1');
insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSS:((2))', 'create_view_PM_E_EBSS_AGGLEVEL', '2', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_E_EBSS_AGGLEVEL'') > 0 
DROP VIEW SELECT_E_EBSS_AGGLEVEL
BEGIN 
create view
  SELECT_E_EBSS_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS)
  as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE
  WHERE TIMELEVELBH = ''DAYBH''
commit
grant select on SELECT_E_EBSS_AGGLEVEL to dcbo
END', '0');
insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSW:((2))', 'create view SELECT_PM_E_EBSW_AGGLEVEL', '1', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_PM_E_EBSW_AGGLEVEL'') > 0 DROP VIEW SELECT_PM_E_EBSW_AGGLEVEL BEGIN create view SELECT_PM_E_EBSW_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS) as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE WHERE TIMELEVELBH = ''DAYBH'' commit grant select on SELECT_PM_E_EBSW_AGGLEVEL to dcbo END', '1');
insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSW:((2))', 'create_view_PM_E_EBSW_AGGLEVEL', '3', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_E_EBSW_AGGLEVEL'') > 0 
DROP VIEW SELECT_E_EBSW_AGGLEVEL
BEGIN 
create view
  SELECT_E_EBSW_AGGLEVEL(FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS)
  as select FIRSTDATE_ID,AGGLEVEL,DATE_ID,YEAR_ID,MONTH_ID,DAY_ID,WEEK_ID,WEEKDAY_ID,BUSINESSDAY,
  TIMELEVEL,TIMELEVELBH,DAYS from dc.SELECT_AGGLEVEL_TABLE
  WHERE TIMELEVELBH = ''DAYBH''
commit
grant select on SELECT_E_EBSW_AGGLEVEL to dcbo
END', '0');
insert into Externalstatement (VERSIONID, STATEMENTNAME, EXECUTIONORDER, DBCONNECTION, STATEMENT, BASEDEF) values ('PM_E_EBSW:((2))', 'create_view_SELECT_E_RAN_CELL', '2', 'dwh', 'IF (SELECT count(*) FROM sys.sysviews where viewname = ''SELECT_E_RAN_CELL'') > 0 DROP VIEW SELECT_E_RAN_CELL begin create view dc.SELECT_E_RAN_CELL( OSS_ID, CELL_NAME, CELL_ID, SELECTION, SELECTIONGROUP, SELECTIONTYPE, NW_TYPE) as select OSS_ID, CELL_NAME, CELL_ID, SELECTION, SELECTION_GROUP, SELECTION_TYPE, NW_TYPE  from dc.SELECT_RAN_CELL WHERE SELECTION_GROUP=''ERICSSON'' OR SELECTION_TYPE=''AREA'' END', '0');
