insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('94', 'PM_E_EBSG', 'TechPack PM_E_EBSG ((2)) by TPIDE b', '((3))', 'Y', 'Techpack');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('95', 'INTF_PM_E_EBSG', 'Interface INTF_PM_E_EBSG by TPIDE b', '((101))', 'N', 'Interface');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('96', 'PM_E_EBSS', 'TechPack PM_E_EBSS ((2)) by TPIDE b', '((2))', 'Y', 'Techpack');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('97', 'INTF_PM_E_EBSS', 'Interface INTF_PM_E_EBSS by TPIDE b', '((101))', 'N', 'Interface');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('98', 'PM_E_EBSW', 'TechPack PM_E_EBSW ((2)) by TPIDE b', '((2))', 'Y', 'Techpack');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('99', 'INTF_PM_E_EBSW', 'Interface INTF_PM_E_EBSW by TPIDE b', '((101))', 'N', 'Interface');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('179', 'INTF_PM_E_EBSW-eniq_oss_1', 'Interface INTF_PM_E_EBSW by TPIDE b', '((101))', 'Y', 'Interface');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('202', 'INTF_PM_E_EBSG-eniq_oss_1', 'Interface INTF_PM_E_EBSG by TPIDE b', '((101))', 'Y', 'Interface');
insert into Meta_collection_sets (COLLECTION_SET_ID, COLLECTION_SET_NAME, DESCRIPTION, VERSION_NUMBER, ENABLED_FLAG, TYPE) values ('242', 'INTF_PM_E_EBSS-eniq_oss_1', 'Interface INTF_PM_E_EBSS by TPIDE b', '((101))', 'Y', 'Interface');
