insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSG', 'ACTIVE', 'PM_E_EBSG_TRX', 'RAW', '-1', 'Measurement', 'large_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSG', 'ACTIVE', 'PM_E_EBSG_TRX', 'DAY', '-1', 'Measurement', 'large_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSG', 'ACTIVE', 'PM_E_EBSG_CELL', 'RAW', '-1', 'Measurement', 'large_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSG', 'ACTIVE', 'PM_E_EBSG_CELL', 'DAY', '-1', 'Measurement', 'large_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE) values ('PM_E_EBSG', 'ACTIVE', 'SELECT_PM_E_EBSG_AGGLEVEL', 'PLAIN', '-1', 'Reference');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_RA', 'RAW', '-1', 'Measurement', 'small_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_RA', 'DAY', '-1', 'Measurement', 'small_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_SA', 'DAY', '-1', 'Measurement', 'small_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_SA', 'RAW', '-1', 'Measurement', 'small_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_TAC', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_TAC', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_GGSN', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_GGSN', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HNI', 'RAW', '-1', 'Measurement', 'small_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HNI', 'DAY', '-1', 'Measurement', 'small_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_CELL', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_CELL', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HZI', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HZI', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_SGSN', 'DAY', '-1', 'Measurement', 'small_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_SGSN', 'RAW', '-1', 'Measurement', 'small_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HLR', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_HLR', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_APN', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_APN', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_TACSVN', 'RAW', '-1', 'Measurement', 'medium_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSS', 'ACTIVE', 'PM_E_EBSS_TACSVN', 'DAY', '-1', 'Measurement', 'medium_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE) values ('PM_E_EBSS', 'ACTIVE', 'SELECT_PM_E_EBSS_AGGLEVEL', 'PLAIN', '-1', 'Reference');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSW', 'ACTIVE', 'PM_E_EBSW_CELL', 'DAY', '-1', 'Measurement', 'large_day');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE, PARTITIONPLAN) values ('PM_E_EBSW', 'ACTIVE', 'PM_E_EBSW_CELL', 'RAW', '-1', 'Measurement', 'large_raw');
insert into TypeActivation (TECHPACK_NAME, STATUS, TYPENAME, TABLELEVEL, STORAGETIME, TYPE) values ('PM_E_EBSW', 'ACTIVE', 'SELECT_PM_E_EBSW_AGGLEVEL', 'PLAIN', '-1', 'Reference');
