insert into Universename (VERSIONID, UNIVERSENAME, UNIVERSEEXTENSION, UNIVERSEEXTENSIONNAME) values ('PM_E_EBSG:((3))', 'DCE37', '', '');
insert into Universename (VERSIONID, UNIVERSENAME, UNIVERSEEXTENSION, UNIVERSEEXTENSIONNAME) values ('PM_E_EBSS:((2))', 'DCE38', '', '');
insert into Universename (VERSIONID, UNIVERSENAME, UNIVERSEEXTENSION, UNIVERSEEXTENSIONNAME) values ('PM_E_EBSW:((2))', 'DCE36', '', '');
