package com.ericsson.eniq.teststubs;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * A stub implementation for java.sql.Statement interface. This class is used
 * by the ConnectionStub as a result for createStatement() method.
 * 
 * @author epiituo
 */
public class StatementStub implements Statement {

	
	public void addBatch(String sql) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void cancel() throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void clearBatch() throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void clearWarnings() throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void close() throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public boolean execute(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public int[] executeBatch() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	
	public ResultSet executeQuery(String sql) throws SQLException {
		return new ResultSetStub();
	}

	
	public int executeUpdate(String sql) throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public Connection getConnection() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	
	public int getFetchDirection() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int getFetchSize() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public ResultSet getGeneratedKeys() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	
	public int getMaxFieldSize() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int getMaxRows() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public boolean getMoreResults() throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public boolean getMoreResults(int current) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public int getQueryTimeout() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public ResultSet getResultSet() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	
	public int getResultSetConcurrency() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int getResultSetHoldability() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int getResultSetType() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public int getUpdateCount() throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	
	public SQLWarning getWarnings() throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	
	public boolean isClosed() throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public boolean isPoolable() throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public void setCursorName(String name) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setEscapeProcessing(boolean enable) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setFetchDirection(int direction) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setFetchSize(int rows) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setMaxFieldSize(int max) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setMaxRows(int max) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setPoolable(boolean poolable) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public void setQueryTimeout(int seconds) throws SQLException {
		// TODO Auto-generated method stub

	}

	
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

	
	public <T> T unwrap(Class<T> iface) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public void closeOnCompletion() throws SQLException {
		// TODO Auto-generated method stub
		
	}


	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		// TODO Auto-generated method stub
		return false;
	}

}
